# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI  # optional

on: # required, name of Github event that triggers the workflow
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs: # required
# each job in a work flow runs in a fresh virtual environment
# can be one or more
# sequence of task
# steps can run commands,setup tasks Or run an action

  build: # building the application
    runs-on: ubuntu-latest # can be runs on linux,window,mac  
    steps:
    - uses: actions/checkout@v3 # select an action , under path action/ the reusable code is hosted

    - name: pulling git repo
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.3
    - name: install all dependencies
      run: |
        go version
        go get -u github.com/gin-gonic/gin

    - name: Building the instagram-app
      run: go build -v ./...

  test: # testing the application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: pulling git repo
      uses: actions/setup-go@v3
      
    - name: Testing the instagram-app
      run: go test -v ./...

  deploy: # deploy on docker hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push to docker hub registery
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: cicd-demo
        
